import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <h3><a href="/navbar">Navbar</a></h3>
        <h3><a href="/">about</a></h3>
        <h3><a href="/">Home</a></h3>
         <footer className="w-full border-t border-gray-200 p-4 text-center text-sm text-gray-500">
        Copyright © 2024 | Baqir Al Musawi | 21612428 |
        </footer>
      </body>
    </html>
  );
}
